# Generated by Django 5.1.1 on 2024-09-29 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdviceApp', '0003_remove_advice_apiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
