# Generated by Django 5.1.1 on 2024-09-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdviceApp', '0004_advice_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='added',
        ),
    ]
